on: [push]
name: Test setup kubectl


jobs:
   setup-kubectl:
      runs-on: ubuntu-latest  
      steps:
         #  - uses: actions/checkout@v3
         #  - name: Install kubectl
         #    uses: './setup-kubectl'
         #  - run: kubectl

         - uses: yangyu823/setup-kubectl-v1@latest
           with:
              version: `v1.16.0` # default is latest stable
           id: install
