name: 'Manual unit tests.'
on: # rebuild any PRs and main branch changes
   workflow_dispatch:
    branches:
      - main
    inputs:
      lock_id:
        type: choice
        options:
          - np
          - prod

jobs:
   build: # make sure build/ci works properly
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1

         - name: Build and run L0 tests.
           run: |
              npm install
              npm test
